#if !canImport(ObjectiveC)
import XCTest

extension DiffTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DiffTests = [
        ("testUniverseWorks", testUniverseWorks),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DiffTests.__allTests__DiffTests),
    ]
}
#endif
